apiVersion: v1
kind: ConfigMap
metadata:
  name: zcp-iam-config
  namespace: zcp-system
data:
  SPRING_ACTIVE_PROFILE: stage 
  MARIADB_HOST: bk-mariadb-mariadb.bk-service
  MARIADB_USER: zcp-user
  REDIS_HOST: bk-redis-redis.bk-service
